Show Databases;
Create Database SmartBridge;
Use SmartBridge;
Create Table Week_1 ( Id Int Primary Key, FName Varchar(100) , LName Varchar(100));
Insert Into Week_1 Value(1 , 'Madhur' , 'Agarwal');
Insert Into Week_1 Value(2 , 'Sparsh' , 'Jain');
Insert Into Week_1 Value(3 , 'Ankit' , 'Priyadarshi');
Insert Into Week_1 Value(4 , 'Pranjal' , 'Singhal');
Select * from Week_1;
Update Week_1 Set LName = 'Fulwani' Where Id = '4';
Delete From Week_1 where Id = '1';
Create Table Week_2 ( Id Int Primary Key, Age Int);
Insert Into Week_2 Values(1 , 21);
Insert Into Week_2 Values(2 , 20);
Insert Into Week_2 Values(3 , 22);
Insert Into Week_2 Values(4 , 17);
Select * from Week_2;
Select * from Week_2 Join Week_1 on Week_1.Id = Week_2.Id;
Select * from Week_2 Right Join Week_1 on Week_1.Id = Week_2.Id;
Select * from Week_2 Left Join Week_1 on Week_1.Id = Week_2.Id;
Select * from Week_2 Inner Join Week_1 on Week_1.Id = Week_2.Id;
